### ISSUE TITLE
Investigate Closure Tree as a Dependency

### ISSUE THREAD

**Issue by DerekStride** [DerekStride/competency-tracker#29]
@esfandia @babakesfandiari (not sure which to ping)

I was introduced to an interesting ruby gem that helps with modelling tree structures in ActiveRecord. It might simplify the code for competencies and pre/postrequisites. It even adds a `to_dot_digraph` method that can build graphviz views.

https://github.com/mceachen/closure_tree

**Comment by esfandia** [comment]
That's very cool!

**Comment by esfandia** [comment]
Here's a little project that renders Graphviz in the browser: https://github.com/mdaines/viz.js
